name: pose-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.3
  - pandas=2.0.3
  - pyarrow=12.0.1
  - pip:
    - mediapipe==0.10.9
    - opencv-python==4.8.1.78
    - open3d==0.18.0
    - click==8.1.7
